import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import Menu from "@/components/menu/Menu";
import BackgroundLine from "@/components/backgroundLine/BackgroundLine";
import Prototype from "@/components/prototype/Prototype";
import Frontend from "@/components/Frontend/Frontend";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Luke Fitzpatrick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="headerdiv">
          <Header />
        </div>

        <div className="row container-fluid position-absolute justify-content-center">
          <div className="col-11">
            <BackgroundLine />
          </div>
        </div>
        <div>
          <Menu />
        </div>
        <div className="mt-5">
          <Prototype />
        </div>
        {/* <div> */}
        <Frontend />
        {/* </div> */}
        <div className="headerdiv "></div>
      </main>
    </>
  );
}
